Deprecating chartrepo

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,6 +1,7 @@
 variables:
-  HELM_VERSION: v3.5.2
-  HELM_CHART_REPO: sciencebox
+  HELM_VERSION: v3.10.3
+  REGISTRY: registry.cern.ch
+  REGISTRY_CHART_REPO: sciencebox
 
 stages:
   - build
@@ -13,7 +14,7 @@ build:
   stage: build
   image: gitlab-registry.cern.ch/cloud/ciadm
   script:
-    - curl -o helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz; mkdir -p helm; tar zxvf helm.tar.gz -C helm; cp helm/linux-amd64/helm /usr/local/bin; rm -rf helm*
+    - curl -o helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz; mkdir -p helm; tar zxvf helm.tar.gz -C helm; /usr/bin/cp helm/linux-amd64/helm /usr/local/bin; rm -rf helm*
     - for chart in $(ls -d */Chart.yaml | xargs dirname); do helm dep update ${chart}; helm lint ${chart}; helm package ${chart}; done
   except:
     - tags
@@ -60,15 +61,34 @@ deploy:
   stage: deploy
   image: gitlab-registry.cern.ch/cloud/ciadm
   before_script:
-    - curl -o helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz; mkdir -p helm; tar zxvf helm.tar.gz -C helm; cp helm/linux-amd64/helm /usr/local/bin; rm -rf helm*
+    - curl -o helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz; mkdir -p helm; tar zxvf helm.tar.gz -C helm; /usr/bin/cp helm/linux-amd64/helm /usr/local/bin; rm -rf helm*
   script:
-    - helm repo add ${HELM_CHART_REPO} https://registry.cern.ch/chartrepo/${HELM_CHART_REPO}
-    - helm repo update
-    - helm plugin install https://github.com/chartmuseum/helm-push
     - |
         set -x
         CHART=$(echo $CI_COMMIT_TAG | awk -F '@' '{print $1}')
-        helm dependency update ${CHART}
-        helm cm-push ${CHART}/ ${HELM_CHART_REPO}
+        TAG_VERSION=$(echo $CI_COMMIT_TAG | awk -F '@' '{print $2}')
+
+        test -f ${CHART}/Chart.yaml
+        if [ $? -ne 0 ]; then
+          echo "ERROR: Chart.yaml does not exist for chart ${CHART}"
+          exit 1
+        fi
+        YAML_VERSION=$(cat ${CHART}/Chart.yaml | grep ^version | awk '{print $2}')
+        if [[ "$TAG_VERSION" == "$YAML_VERSION" ]]; then
+          echo "INFO: Logging to ${REGISTRY} as ${HELM_REPO_USERNAME}"
+          echo ${HELM_REPO_PASSWORD} | helm registry login ${REGISTRY} -u ${HELM_REPO_USERNAME} --password-stdin
+
+          echo "INFO: Linting and packaging ${CHART}"
+          helm dependency update ${CHART}
+          helm lint ${CHART}
+          helm package ${CHART}
+
+          REGISTRY_CHART_URL="${REGISTRY}/${REGISTRY_CHART_REPO}/charts"
+          echo "INFO: Will push ${CHART} (version ${TAG_VERSION}) to ${REGISTRY_CHART_URL}"
+          helm push ${CHART}-${TAG_VERSION}.tgz oci://${REGISTRY_CHART_URL}
+        else
+          echo "ERROR: Chart version ($YAML_VERSION) differs from tag version ($TAG_VERSION)"
+          exit 1
+        fi
   only:
     - tags
